### PR TITLE
Modifications for gpu testing framework

### PR DESCRIPTION
**Pull request by sherimickelson**
Modified the Makefile to be more flexible
 - options include: FC, USE_MPI, USE_OPENMP, USE_DOUBLE, USE_OPENACC, DEBUG
 - example: ``FC=pgf90 USE_MPI=false USE_OPENMP=false USE_DOUBLE=false USE_OPENACC=false DEBUG=true``

Added the ability to read in a specified namelist file.  This is done through an optional command line argument ``--namelist`` The default is "namelist.input".  Example of how to read in a different namelist: ``--namelist namelist.asd04-128x1k.input``

### CODE REVIEW

**Comment by sherimickelson** [comment]
These changes are designed to work with 
https://github.com/sherimickelson/CM1_benchmarkingWF

To run the test suite, modify the top of the runit file and then execute that file.

**Comment by sjsprecious** [comment]
Hi @sherimickelson , thanks for your update. I checked out the latest `gpu-opt` branch of CM1 Repo (commit: `c5e2be3`) and merged your changes. Then I checked out your Repo (https://github.com/sherimickelson/CM1_benchmarkingWF) and revised the `runit` script for some paths/ID (no changes to the compiler options). Then I ran the `runit` script by `./runit`. The output contained the message `Success!!! Job is in the queue.` but it was followed by the error message immediately: 
```
Traceback (most recent call last):
  File "./runit", line 150, in <module>
    with open(json_file, 'w') as f:
IOError: [Errno 2] No such file or directory: 'logs/files.json'
```
Let me know if I did anything wrong here.

**Comment by sherimickelson** [comment]
@sjsprecious, thanks for trying the code out.  Could you create a directory called "logs" in your CM1_benchmarkingWF directory and see if the error still appears?

**Comment by sjsprecious** [comment]
Thanks @sherimickelson. After manually generating the `logs` folder under the `CM1_benchmarkingWF` directory, I did not see the previous error but encountered the following one:
```
nvlink error   : Undefined reference to 'parcel_module_find_vertical_location_index_' in 'parcel.o'
nvlink error   : Undefined reference to 'parcel_module_find_horizontal_location_index_' in 'parcel.o'
pgacclnk: child process exit status 2: /glade/u/apps/opt/nvhpc/21.11/Linux_x86_64/21.11/compilers/bin/tools/nvdd
make: *** [cm1] Error 2
mv: cannot stat ‘../run/cm1.exe’: No such file or directory
ERROR: Problem while building
```
With this error message, I could find the executables `cm1-debug.exe` and `cm1-mpi-openacc-debug.exe` under the `run` directory, but not the `cm1-openacc-debug.exe`.

**Comment by sjsprecious** [comment]
And the `cm1-mpi-openacc-debug.exe` test run fails with the following error message:
```
FATAL ERROR: variable in data clause is partially present on the device: name=tmass
 file:/glade/scratch/sunjian/CM1/src/misclibs.f90 totmois line:3524

compared 295 blocks, 898427260 elements, 3593709136 bytes
1443305 errors found in 111 blocks
 absolute tolerance = 1.00000000000000008e-15, abs=15
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[61595,1],0]
  Exit code:    1
```

**Comment by sherimickelson** [comment]
@sjsprecious I'm glad that fixed the first problem.  As for the build and run problems, those were the same problems I was seeing.  Maybe we can talk about them during our meeting this afternoon?

**Comment by johnmauff** [comment]
This appears to be an issue that is triggered when the _B4B flag is enabled.  I have done most of my testing lately without the _B4B flag which explains why I have not encountered this issue.

**Comment by sjsprecious** [comment]
> This appears to be an issue that is triggered when the _B4B flag is enabled. I have done most of my testing lately without the _B4B flag which explains why I have not encountered this issue.

Oh, my bad. I checked out the latest `gpu-opt` branch but forgot to comment out the `_B4B` flag. I would do another test with this flag turned off. Thanks @johnmauff for pointing this out!

**Comment by sjsprecious** [comment]
After I commented out the `_B4B` flag and rebuilt/reran the `runit` script, I got the following runtime error for the `cm1-mpi-openacc-debug.exe` test:
```
call to cuStreamSynchronize returned error 700: Illegal address during kernel execution

compared 623 blocks, 2581904654 elements, 10327647616 bytes
195118334 errors found in 264 blocks
614 errors tolerated in 6 blocks
 absolute tolerance = 1.00000000000000008e-15, abs=15
```
And the same build error for the `cm1-openacc-debug.exe` test before still existed.

**Comment by sjsprecious** [comment]
Disabling the `DEBUG` flag (`DEBUG=FALSE`) in the `runit` script will resolve the build error for `cm1-openacc-debug.exe` test and this test could be built successfully now.

**Comment by sjsprecious** [comment]
@sherimickelson @johnmauff Ok, I have a fix to the multi-MPI-GPU runtime error in this PR https://github.com/george-bryan/CM1/pull/26. After revising the source code, I am able to use this verification framework to run the MPI, one GPU and multi-MPI-GPU tests with different namelist input. The only failed test now is the multi-MPI-GPU one with the "**namelist.sas.input**" input. The error message says "**Courant number has exceeded 1.5**". It looks like a namelist issue rather than a code bug?

**Comment by sjsprecious** [comment]
And one more minor comment: when we have more tests running, the root directory of `CM1_benchmarkingWF` becomes messy. Is it better to move all the shell scripts and PBS output to the `logs` folder?

**Comment by johnmauff** [comment]
The courant number exceeded 1.5 is a bug that has been present in the CM1 code for a while.  WHile it was revealed by the testing framework addition, it is fundamentally unrelated to Sheri's changes.  So I approve of this pull request.

**Review by johnmauff — APPROVED** [review]

**Review by sjsprecious — APPROVED** [review]

**Comment by johnmauff** [comment]
Add verification test capabilitiy

**Pull request merged**
