### PR TITLE
Sub-PR 3

### PR DESCRIPTION
**Pull request by drichte2**
The main point of this is to move the droplet_diag write subroutine into droplets.F from writeout_nc.F. This allows for certain droplet diagnostics to be defined in the droplet module for convenience.

### CODE REVIEW

**Comment by sjsprecious** [comment]
By using the namelist `namelist.restC`, the verification result on Casper looks below:

---

CPU (intel, 2 MPI ranks) vs. GPU (nvhpc, 2 MPI ranks + 2 V100 GPUs)

Stat output comparision

Identical variables: 62
variables with rel_diff > 1.e-6: 24
variables with rel_diff <= 1.e-6: 0
four variables with largest error: PPMIN, PPMAX, VOR2KM, DIVMAX

Droplet 0th-order diagnostic comparision

Identical variables: 10
variable with rel_diff > 1.e-6: 2
variable with rel_diff <= 1.e-6: 0
Two variables with largest error: Tpavg (~3.4e-6), radmin (~6.2e-6)

Droplet 1st-order diagnostic comparision

Identical variables: 512
variable with rel_diff > 1.e-6: 0
variable with rel_diff <= 1.e-6: 0

---

Compared to the PR #103, the stat output comparison result shows one fewer identical variable and one more variable with relative difference >1.e-6. The droplet diagnostic is consistent.

**Comment by johnmauff** [comment]
Which diagnostic variable changed with this PR?

**Comment by sjsprecious** [comment]
@johnmauff it is weird that I just re-ran the PR #103 on Casper and also got 62 identical variables and 24 variables with relative difference > 1.e-6 now. Unfortunately I did not save the log files for the "63 identical variables" case and thus I did not know which variable changed the result here.

**Comment by sjsprecious** [comment]
@johnmauff, it turns out that the difference comes from the conda environment on Casper. If I run the verification test within a conda environment, there are "63 identical variables" between CPU and GPU runs. If I run the verification test without a conda environment,  there are "62 identical variables". The different stat variable is `MAXqv` and the relative difference is about 5e-6.

**Review by sjsprecious — APPROVED** [review]

**Review by johnmauff — APPROVED** [review]
This PR looks good.

**Pull request merged**
