### PR TITLE
Port of fallout and satadj to GPU

### PR DESCRIPTION
**Pull request by sherimickelson**

### CODE REVIEW

**Review by johnmauff — COMMENTED** [review]
What kind of speedup are you achieving with your GPU port for each subroutine

**Comment by sherimickelson** [comment]
This was what I saw for fallout:
Before port:
```fallout  :        5.26    1.12%```
After port:
``` fallout  :        2.47    0.54%```
I ended up on a busy node for the satadj port so my numbers might not reflect accurate performance.

**Comment by johnmauff** [comment]
Bummer that is not the speedup I was  hoping for.  At least that is an improvement over the CPU resident version.  What about satadj?

**Comment by sherimickelson** [comment]
I ended up on a busy node so I'm not sure I trust these timings, but here's what I saw for satadj:
Before port:
```satadj   : 3.91    0.97%```
After port:
```satadj   : 1.50    0.33%```

**Pull request merged**
